{% set name = "labeling" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/labeling-{{ version }}.tar.gz
  sha256: fceaa24e3c5d88d2bfa17ea5356503553be726dc3395563358266c9c6fac8b87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - pillow
    - python >={{ python_min }}
    - tifffile
    - scipy

test:
  imports:
    - labeling
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Labelings/pyLabeling
  summary: A package to create labeling/segmentation information based on pixel values.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tomburke-rse
